import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import readline from 'node:readline';
import crypto from 'node:crypto';
import {
  CLAUDE_PROJECTS_DIR,
  CODEX_SESSIONS_DIR,
  CODEX_SESSION_INDEX,
  INDEX_FILE,
  PJX_DIR,
} from './paths.js';
import type { IndexFile, ScannedProject, Source } from './types.js';

const TRUNC = 500;

function truncate(s: string, n = TRUNC): string {
  if (!s) return '';
  return s.length > n ? s.slice(0, n) + '…' : s;
}

function makeId(source: Source, key: string): string {
  return crypto.createHash('sha1').update(`${source}|${key}`).digest('hex').slice(0, 16);
}

function extractText(content: unknown): string {
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) {
    const parts: string[] = [];
    for (const part of content) {
      if (!part || typeof part !== 'object') continue;
      const p = part as Record<string, unknown>;
      if (p.type === 'text' && typeof p.text === 'string') parts.push(p.text);
      else if (p.type === 'tool_result') {
        const c = p.content;
        if (typeof c === 'string') parts.push(c);
        else if (Array.isArray(c)) {
          for (const cp of c) {
            if (cp && typeof cp === 'object' && (cp as any).type === 'text') {
              parts.push(String((cp as any).text ?? ''));
            }
          }
        }
      }
    }
    return parts.join('\n').trim();
  }
  return '';
}

function isHumanUserMessage(content: unknown): boolean {
  if (typeof content === 'string') return true;
  if (Array.isArray(content)) {
    let hasText = false;
    for (const part of content) {
      if (!part || typeof part !== 'object') continue;
      const t = (part as any).type;
      if (t === 'tool_result') return false;
      if (t === 'text') hasText = true;
    }
    return hasText;
  }
  return false;
}

type SessionInfo = {
  first_user_ts: string;
  first_user_message: string;
  last_user_ts: string;
  last_user_message: string;
  last_assistant_ts: string;
  last_assistant_message: string;
  last_ts: string;
};

type Acc = {
  source: Source;
  name: string;
  path: string | null;
  storage_cwd: string | null;
  key: string;
  entrypoint_counts: Record<string, number>;
  cwd_counts: Record<string, number>;
  sessions: Map<string, SessionInfo>;
  first_seen: string;
  last_active: string;
  last_user_message: string;
  last_user_ts: string;
  last_assistant_message: string;
  last_assistant_ts: string;
  last_session_id: string;
  total_messages: number;
};

function newAcc(source: Source, name: string, p: string | null, key?: string): Acc {
  return {
    source,
    name,
    path: p,
    storage_cwd: null,
    key: key ?? name,
    entrypoint_counts: {},
    cwd_counts: {},
    sessions: new Map(),
    first_seen: '',
    last_active: '',
    last_user_message: '',
    last_user_ts: '',
    last_assistant_message: '',
    last_assistant_ts: '',
    last_session_id: '',
    total_messages: 0,
  };
}

function update(acc: Acc, ts: string, sessionId: string) {
  if (!acc.first_seen || ts < acc.first_seen) acc.first_seen = ts;
  if (!acc.last_active || ts > acc.last_active) {
    acc.last_active = ts;
    acc.last_session_id = sessionId;
  }
  acc.total_messages += 1;
  let s = acc.sessions.get(sessionId);
  if (!s) {
    s = {
      first_user_ts: '',
      first_user_message: '',
      last_user_ts: '',
      last_user_message: '',
      last_assistant_ts: '',
      last_assistant_message: '',
      last_ts: ts,
    };
    acc.sessions.set(sessionId, s);
  }
  if (ts > s.last_ts) s.last_ts = ts;
}

function recordSessionUserText(acc: Acc, sessionId: string, ts: string, text: string) {
  if (!sessionId || !text) return;
  const s = acc.sessions.get(sessionId);
  if (!s) return;
  if (!s.first_user_ts || ts < s.first_user_ts) {
    s.first_user_ts = ts;
    s.first_user_message = text;
  }
  if (!s.last_user_ts || ts > s.last_user_ts) {
    s.last_user_ts = ts;
    s.last_user_message = text;
  }
}

function recordSessionAssistantText(acc: Acc, sessionId: string, ts: string, text: string) {
  if (!sessionId || !text) return;
  const s = acc.sessions.get(sessionId);
  if (!s) return;
  if (!s.last_assistant_ts || ts > s.last_assistant_ts) {
    s.last_assistant_ts = ts;
    s.last_assistant_message = text;
  }
}

const TOOL_RESULT_HINTS = [
  'tool_use_id',
  'has been updated',
  'File created successfully',
  'updated successfully',
  '<system-reminder>',
  'Updated task #',
  '[Request interrupted',
  'has been denied',
];

const AUTO_INJECTED_PREFIXES = [
  'Base directory for this skill',
  '<scheduled-task',
  '<command-name>',
  '<command-message>',
  '<bash-input>',
  '<local-command-caveat>',
  '<local-command-stdout>',
  '<local-command-stderr>',
  'Caveat: The messages below were generated by the user',
  '<command-stdout>',
  '<command-stderr>',
  // Codex
  '<environment_context>',
  '<turn_aborted>',
  '<user_instructions>',
  '<repo_state>',
  '# AGENTS.md',
  '[external_agent_tool_call:',
];

function looksLikeUserText(text: string): boolean {
  if (!text) return false;
  const trimmed = text.trim();
  if (!trimmed) return false;
  if (trimmed.length < 3) return false;
  if (trimmed.startsWith('{') || trimmed.startsWith('[')) return false;
  for (const h of TOOL_RESULT_HINTS) if (trimmed.includes(h)) return false;
  for (const p of AUTO_INJECTED_PREFIXES) if (trimmed.startsWith(p)) return false;
  return true;
}

function stripSlashCommandWrappers(text: string): string {
  if (!text) return text;
  let t = text;
  t = t.replace(/<local-command-caveat>[\s\S]*?<\/local-command-caveat>/g, '');
  t = t.replace(/<command-name>[\s\S]*?<\/command-name>/g, '');
  t = t.replace(/<command-message>[\s\S]*?<\/command-message>/g, '');
  t = t.replace(/<command-args>[\s\S]*?<\/command-args>/g, '');
  t = t.replace(/<command-stdout>[\s\S]*?<\/command-stdout>/g, '');
  t = t.replace(/<command-stderr>[\s\S]*?<\/command-stderr>/g, '');
  t = t.replace(/<local-command-stdout>[\s\S]*?<\/local-command-stdout>/g, '');
  t = t.replace(/<local-command-stderr>[\s\S]*?<\/local-command-stderr>/g, '');
  t = t.replace(/<bash-input>[\s\S]*?<\/bash-input>/g, '');
  t = t.replace(/<bash-stdout>[\s\S]*?<\/bash-stdout>/g, '');
  t = t.replace(/<bash-stderr>[\s\S]*?<\/bash-stderr>/g, '');
  t = t.replace(/<system-reminder>[\s\S]*?<\/system-reminder>/g, '');
  t = t.replace(/Caveat: The messages below were generated by the user[\s\S]*?\.\s*/g, '');
  return t.trim();
}

async function* readLines(file: string): AsyncGenerator<string> {
  const stream = fs.createReadStream(file, { encoding: 'utf8' });
  const rl = readline.createInterface({ input: stream, crlfDelay: Infinity });
  for await (const line of rl) {
    if (line.trim()) yield line;
  }
}

async function scanClaudeCodeSessionFile(file: string, dirName: string): Promise<Acc | null> {
  const sessionIdFromFile = path.basename(file, '.jsonl');
  const acc = newAcc('claude-code', dirName, null, `claude-code:${sessionIdFromFile}`);
  let saw = false;
  try {
    for await (const line of readLines(file)) {
      let rec: any;
      try {
        rec = JSON.parse(line);
      } catch {
        continue;
      }
      const t = rec?.type;
      if (t !== 'user' && t !== 'assistant') continue;
      const ts: string = rec?.timestamp ?? '';
      const sessionId: string = rec?.sessionId ?? sessionIdFromFile;
      if (!ts) continue;
      const cwd = rec?.cwd;
      if (typeof cwd === 'string' && cwd) {
        acc.cwd_counts[cwd] = (acc.cwd_counts[cwd] ?? 0) + 1;
        // First cwd encountered = cwd at session start. Claude Code's
        // `--resume <id>` lookup is scoped to ~/.claude/projects/<encoded
        // start-cwd>/, so we surface this as storage_cwd for the Resume
        // copy-paste command. Most sessions: storage_cwd === dominant cwd.
        if (!acc.storage_cwd) acc.storage_cwd = cwd;
      }
      const ep = typeof rec?.entrypoint === 'string' ? rec.entrypoint : '';
      if (ep) acc.entrypoint_counts[ep] = (acc.entrypoint_counts[ep] ?? 0) + 1;
      update(acc, ts, sessionId);
      saw = true;
      const content = rec?.message?.content;
      const text = extractText(content);
      if (!text) continue;
      if (t === 'user') {
        const cleaned = stripSlashCommandWrappers(text);
        const human = isHumanUserMessage(content) && looksLikeUserText(cleaned);
        if (human) {
          recordSessionUserText(acc, sessionId, ts, cleaned);
          if (!acc.last_user_ts || ts > acc.last_user_ts) {
            acc.last_user_ts = ts;
            acc.last_user_message = truncate(cleaned);
          }
        }
      } else {
        recordSessionAssistantText(acc, sessionId, ts, text);
        if (!acc.last_assistant_ts || ts > acc.last_assistant_ts) {
          acc.last_assistant_ts = ts;
          acc.last_assistant_message = truncate(text);
        }
      }
    }
  } catch (err) {
    console.error(`[scanner] failed to read ${file}:`, (err as Error).message);
    return null;
  }
  if (!saw) return null;
  const dominantCwd = pickDominantCwd(acc.cwd_counts);
  if (dominantCwd) {
    acc.path = dominantCwd;
    acc.name = path.basename(dominantCwd) || dominantCwd;
  }
  return acc;
}

function pickDominantCwd(counts: Record<string, number>): string | null {
  let best: string | null = null;
  let bestCount = 0;
  for (const [cwd, n] of Object.entries(counts)) {
    if (n > bestCount) {
      best = cwd;
      bestCount = n;
    }
  }
  return best;
}

async function scanClaudeCode(): Promise<Acc[]> {
  if (!fs.existsSync(CLAUDE_PROJECTS_DIR)) return [];
  const out: Acc[] = [];
  const dirs = await fsp.readdir(CLAUDE_PROJECTS_DIR);
  for (const dir of dirs) {
    const full = path.join(CLAUDE_PROJECTS_DIR, dir);
    let stat: fs.Stats;
    try {
      stat = await fsp.lstat(full);
    } catch {
      continue;
    }
    if (stat.isSymbolicLink()) {
      console.warn(`[scanner] skipping symlink: ${full}`);
      continue;
    }
    if (!stat.isDirectory()) continue;
    const entries = await fsp.readdir(full, { withFileTypes: true });
    const files = entries.filter((e) => !e.isSymbolicLink() && e.name.endsWith('.jsonl'));
    for (const f of files) {
      const file = path.join(full, f.name);
      const acc = await scanClaudeCodeSessionFile(file, dir);
      if (acc) out.push(acc);
    }
  }
  return out;
}

async function readCodexThreadNames(): Promise<Map<string, string>> {
  const out = new Map<string, string>();
  if (!fs.existsSync(CODEX_SESSION_INDEX)) return out;
  for await (const line of readLines(CODEX_SESSION_INDEX)) {
    try {
      const rec = JSON.parse(line);
      if (rec?.id && rec?.thread_name) out.set(rec.id, rec.thread_name);
    } catch {
      /* skip */
    }
  }
  return out;
}

function extractCodexText(content: unknown): string {
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) {
    const parts: string[] = [];
    for (const part of content) {
      if (!part || typeof part !== 'object') continue;
      const p = part as Record<string, unknown>;
      const t = p.type;
      if (typeof p.text === 'string' && (t === 'output_text' || t === 'input_text' || t === 'text')) {
        parts.push(p.text);
      }
    }
    return parts.join('\n').trim();
  }
  return '';
}

async function scanCodexRolloutFile(file: string): Promise<Acc | null> {
  // sessionId is the trailing UUID before .jsonl
  const base = path.basename(file, '.jsonl');
  const m = base.match(/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$/i);
  const sessionId = m ? m[1] : base;

  const acc = newAcc('codex', sessionId, null, `codex:${sessionId}`);
  acc.last_session_id = sessionId;
  acc.sessions.set(sessionId, {
    first_user_ts: '',
    first_user_message: '',
    last_user_ts: '',
    last_user_message: '',
    last_assistant_ts: '',
    last_assistant_message: '',
    last_ts: '',
  });
  let saw = false;

  try {
    for await (const line of readLines(file)) {
      let rec: any;
      try {
        rec = JSON.parse(line);
      } catch {
        continue;
      }
      const ts: string = rec?.timestamp ?? '';
      if (!ts) continue;

      // session_meta — extract cwd and originator (entrypoint)
      if (rec?.type === 'session_meta' && rec?.payload) {
        const cwd = rec.payload.cwd;
        if (typeof cwd === 'string' && cwd) {
          acc.path = cwd;
          acc.storage_cwd = cwd;
          acc.name = path.basename(cwd) || cwd;
        }
        const originator = typeof rec.payload.originator === 'string' ? rec.payload.originator : '';
        if (originator) acc.entrypoint_counts[originator] = (acc.entrypoint_counts[originator] ?? 0) + 1;
        if (!acc.first_seen) acc.first_seen = ts;
        continue;
      }

      // event_msg user_message — direct human prompt (preferred source)
      if (rec?.type === 'event_msg' && rec?.payload?.type === 'user_message') {
        const text: string = rec.payload.message ?? '';
        if (text && looksLikeUserText(text)) {
          recordSessionUserText(acc, sessionId, ts, text);
          if (!acc.last_user_ts || ts > acc.last_user_ts) {
            acc.last_user_ts = ts;
            acc.last_user_message = truncate(text);
          }
          update(acc, ts, sessionId);
          saw = true;
        }
        continue;
      }

      // response_item — model interaction (assistant only here; user side has system noise)
      if (rec?.type === 'response_item' && rec?.payload?.type === 'message') {
        const role = rec.payload.role;
        const text = extractCodexText(rec.payload.content);
        if (!text) continue;
        if (role === 'assistant') {
          update(acc, ts, sessionId);
          saw = true;
          recordSessionAssistantText(acc, sessionId, ts, text);
          if (!acc.last_assistant_ts || ts > acc.last_assistant_ts) {
            acc.last_assistant_ts = ts;
            acc.last_assistant_message = truncate(text);
          }
        }
        // role=user from response_item often contains <environment_context> etc; skip it
        // since event_msg user_message above already gives us the human prompt.
      }
    }
  } catch (err) {
    console.error(`[scanner] codex rollout read failed ${file}:`, (err as Error).message);
    return null;
  }

  if (!saw) return null;
  if (!acc.first_seen) acc.first_seen = acc.last_active;
  return acc;
}

async function walkRolloutFiles(dir: string): Promise<string[]> {
  const out: string[] = [];
  let entries: fs.Dirent[];
  try {
    entries = await fsp.readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const e of entries) {
    if (e.isSymbolicLink()) continue;
    const full = path.join(dir, e.name);
    if (e.isDirectory()) {
      const nested = await walkRolloutFiles(full);
      out.push(...nested);
    } else if (e.isFile() && e.name.startsWith('rollout-') && e.name.endsWith('.jsonl')) {
      out.push(full);
    }
  }
  return out;
}

async function scanCodex(): Promise<Acc[]> {
  if (!fs.existsSync(CODEX_SESSIONS_DIR)) return [];
  const threadNames = await readCodexThreadNames();
  const files = await walkRolloutFiles(CODEX_SESSIONS_DIR);
  const accs: Acc[] = [];
  for (const file of files) {
    const acc = await scanCodexRolloutFile(file);
    if (!acc) continue;
    // Apply thread_name as display name when it looks human-readable
    const threadName = threadNames.get(acc.last_session_id);
    if (threadName && !threadName.startsWith('<') && !threadName.startsWith('#')) {
      acc.name = threadName;
    }
    accs.push(acc);
  }
  return accs;
}

function shortLabel(text: string, maxLen = 40): string {
  if (!text) return '';
  let t = text.trim();
  t = t.replace(/^(@[^\s]+\s+)+/, '');
  t = t.replace(/^「[^」]{0,40}」\s*/, '');
  t = t.split(/\n/)[0]?.trim() ?? '';
  if (!t) return '';
  const sentenceRe = new RegExp(`^.{8,${maxLen}}?[。？！\\?\\!]`);
  const m = t.match(sentenceRe);
  if (m) return m[0].replace(/[。\?\!？！]+$/, '');
  if (t.length <= maxLen) return t;
  const cut = t.slice(0, maxLen);
  const lastBreak = Math.max(cut.lastIndexOf('、'), cut.lastIndexOf(' '), cut.lastIndexOf('　'));
  if (lastBreak >= Math.floor(maxLen / 2)) return cut.slice(0, lastBreak);
  return cut + '…';
}

function pickEarliestSession(acc: Acc): SessionInfo | null {
  const candidates: SessionInfo[] = [];
  for (const s of acc.sessions.values()) {
    if (s.first_user_message && s.first_user_message.trim().length >= 8) candidates.push(s);
  }
  if (candidates.length === 0) {
    for (const s of acc.sessions.values()) if (s.first_user_message) candidates.push(s);
  }
  candidates.sort((a, b) => (a.first_user_ts || a.last_ts).localeCompare(b.first_user_ts || b.last_ts));
  return candidates[0] ?? null;
}

function pickLatestSession(acc: Acc): SessionInfo | null {
  let best: SessionInfo | null = null;
  for (const s of acc.sessions.values()) {
    if (!best || s.last_ts > best.last_ts) best = s;
  }
  return best;
}

function deriveProjectLabel(acc: Acc): string {
  const earliest = pickEarliestSession(acc);
  if (earliest?.first_user_message) return shortLabel(earliest.first_user_message, 50);
  return '';
}

function deriveCurrentStatus(acc: Acc): string {
  const latest = pickLatestSession(acc);
  if (!latest) return '';
  const userPart = latest.last_user_message
    ? shortLabel(latest.last_user_message, 70)
    : '';
  const asstPart = latest.last_assistant_message
    ? shortLabel(latest.last_assistant_message, 70)
    : '';
  if (userPart && asstPart) return `直近指示: ${userPart}  /  対応: ${asstPart}`;
  if (userPart) return `直近指示: ${userPart}`;
  if (asstPart) return `直近対応: ${asstPart}`;
  return '';
}

function pickTopic(acc: Acc): string {
  const latest = pickLatestSession(acc);
  if (latest?.first_user_message) return truncate(latest.first_user_message, 200);
  const earliest = pickEarliestSession(acc);
  if (earliest?.first_user_message) return truncate(earliest.first_user_message, 200);
  return '';
}

function pickEntrypoint(acc: Acc): 'cli' | 'desktop' | 'unknown' {
  let best = '';
  let bestCount = 0;
  for (const [k, v] of Object.entries(acc.entrypoint_counts)) {
    if (v > bestCount) {
      best = k;
      bestCount = v;
    }
  }
  if (acc.source === 'codex') {
    // Codex originator values observed: codex-tui, codex_exec, Codex Desktop, Claude Code
    if (best === 'Codex Desktop') return 'desktop';
    if (best === 'codex-tui' || best === 'codex_exec' || best === 'Claude Code') return 'cli';
    return 'cli'; // default for Codex when originator missing
  }
  if (best === 'cli') return 'cli';
  if (best === 'claude-desktop' || best === 'desktop') return 'desktop';
  return 'unknown';
}

function toProject(acc: Acc): ScannedProject {
  const key = acc.key;
  const topic = pickTopic(acc);
  const project_label = deriveProjectLabel(acc);
  const current_status = deriveCurrentStatus(acc);
  return {
    id: makeId(acc.source, key),
    source: acc.source,
    entrypoint: pickEntrypoint(acc),
    name: acc.name,
    path: acc.path,
    storage_cwd: acc.storage_cwd ?? acc.path,
    session_count: acc.sessions.size,
    first_seen: acc.first_seen,
    last_active: acc.last_active,
    last_user_message: acc.last_user_message,
    last_assistant_message: acc.last_assistant_message,
    last_session_id: acc.last_session_id,
    total_messages: acc.total_messages,
    project_label,
    current_status,
    topic,
    auto_label: project_label,
  };
}

async function atomicWrite(file: string, data: string): Promise<void> {
  await fsp.mkdir(path.dirname(file), { recursive: true });
  const tmp = `${file}.tmp.${process.pid}.${Date.now()}`;
  await fsp.writeFile(tmp, data, 'utf8');
  await fsp.rename(tmp, file);
}

export async function scan(): Promise<IndexFile> {
  await fsp.mkdir(PJX_DIR, { recursive: true });
  const [cc, cx] = await Promise.all([scanClaudeCode(), scanCodex()]);
  const projects = [...cc, ...cx]
    .map(toProject)
    .filter((p) => p.last_active)
    .sort((a, b) => (a.last_active < b.last_active ? 1 : -1));
  const file: IndexFile = {
    generated_at: new Date().toISOString(),
    projects,
  };
  await atomicWrite(INDEX_FILE, JSON.stringify(file, null, 2));
  return file;
}

